### ISSUE TITLE
Bug: Staff-log glitches

### ISSUE THREAD

**Issue by PostMoe** [Nekorooni/Kiara#9]
Sometimes when doing bans or kicks, Kiara refuses to post a proper staff log. Instead posting an embedded message that says "case".
Hard to re-produce but has been a recurring bug for a while now.

**Comment by Nekorooni** [comment]
Yeah I've seen it happen too and I know what's causing it.

The bug happens when using the ban command with a reason surrounded in quotes, since these arent getting escaped right, so it adds double quotes causing the sql query to fuck up.
The commands take anything after the user argument as reason, so surrounding it in quotes isn't required.

I honestly forgot about this so thanks for the reminder. I'll fix it when I can.
